export const lang = {
  en: {
    learnFinance: "Learn Finance",
    greeting: "Hi, ",
    login: "Login",
    logout: "Logout",
    loginAsGuest: "Login with Guest account",
    loginText: "Already have an account? Login now!",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    password: "Password",
    signup: "Create my account",
    signupText: "Don't have an account? Signup now!",
    home: "Home",
    playlist: "Playlist",
    likedVideos: "Liked Videos",
    history: "Watch History",
    clearHistory: "Clear History",
    saveTo: "Save to..",
    enterPlaylistName: "Enter playlist name..",
    noPlaylist: "No playlist",
    emptyPlaylist: "you have no playlist.. wanna create one?",
    playlistError: "Could not get your playlist",
    emptyHistory: "This list has no videos",
    createAndSave: "Create and save",
    playlistName: "Playlist Name",
    seeVideos: "See videos",
    seemsEmpty: "seems empty :(",
    videos: "videos",
    views: "views",
    videosError: "could not get videos :("
  },
  hi: {
    learnFinance: "लर्न फाइनेंस",
    greeting: "नमस्ते, ",
    login: "साइन-इन करें",
    logout: "लॉग आउट",
    loginAsGuest: "अतिथि के रूप में लॉगिन करें",
    loginText: "पहले से ही एक अकाउंट है? अभी लॉगिन करें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signup: "मेरा अकाउंट बनाएं",
    signupText: "अकाउंट नहीं है? अकाउंट बनाएं",
    home: "होम पेज",
    playlist: "प्लेलिस्ट",
    likedVideos: "पसंद किए गए वीडियो",
    history: "देखे गए वीडियो",
    clearHistory: "वीडियो इतिहास मिटा दें",
    saveTo: "इस पर सेव करें..",
    enterPlaylistName: "प्लेलिस्ट का नाम डालें..",
    noPlaylist: "कोई प्लेलिस्ट नहीं",
    emptyPlaylist: "कोई प्लेलिस्ट नहीं",
    playlistError: "आपकी प्लेलिस्ट नहीं मिल सकी",
    emptyHistory: "इस सूची में कोई वीडियो नहीं है",
    createAndSave: "बनाएँ और सेव करें",
    playlistName: "प्लेलिस्ट नाम",
    seeVideos: "वीडियो देखें",
    seemsEmpty: "खाली लगता है :(",
    videos: "वीडियो",
    views: "बार देखा गया",
    videosError: "वीडियो नहीं मिल सका :("
  }
};
